In [2]:
pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Vojas Gonnade\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
pip show torch

Name: torch
Version: 2.3.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\vojas gonnade\appdata\local\programs\python\python310\lib\site-packages
Requires: filelock, fsspec, jinja2, mkl, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch

In [5]:
# Tensors
# A tensor is a number, vector, matrix, or any nd array. 

In [6]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
t2 = torch.tensor([1.,2.,3])   # 3 gets converted to 3.0
t2

tensor([1., 2., 3.])

In [9]:
t3 = torch.tensor([[2,3],[4,2],[1,4]])
t3

tensor([[2, 3],
        [4, 2],
        [1, 4]])

In [10]:
t4 = torch.tensor([[2,3],[4,2,4],[1,4]])
t4

ValueError: expected sequence of length 2 at dim 1 (got 3)

In [11]:
t1.shape

torch.Size([])

In [12]:
t2.shape

torch.Size([3])

In [13]:
t3.shape

torch.Size([3, 2])

In [14]:
# Tensor Operations and gradients

In [17]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad = True)
b = torch.tensor(5.,requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [18]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [29]:
# Compute Derivatives

y.backward()  # it goes backward and sees which has requires_grad = True

# the derivatives of y wrt input tensors are stores in the .grad property

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [26]:
print(x.grad)     # None beacuse we didnt gave requires_grad = True

None


In [27]:
print(w.grad)

tensor(3.)


In [28]:
print(b.grad)

tensor(3.)


In [30]:
# Interoperability with NUmpy

In [31]:
import numpy as np
x = np.array([[1,2],[3,4.]])

In [32]:
x

array([[1., 2.],
       [3., 4.]])

In [33]:
# Torch from numpy

y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [34]:
x.dtype

dtype('float64')

In [35]:
y.dtype

torch.float64

In [38]:
# Numpy from torch
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])